//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerce.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    
    public partial class Product
    {
        public Product()
        {
            this.PurchaseHistories = new HashSet<PurchaseHistory>();
        }
    
        public int Id { get; set; }
        [Required, DisplayName("Product Name")]
        public string Name { get; set; }
        [Required, DisplayName("Category")]
        public int CategoryId { get; set; }
        [Required, DisplayName("Brand")]
        public int BrandId { get; set; }
        [Required]
        public string Description { get; set; }
        public string Image { get; set; }
        [Required,Range(1,9999,ErrorMessage="Invalid Quantity")]
        public int Quantity { get; set; }
        [Required,Range(0,double.MaxValue,ErrorMessage="Invalid Price")]
        public decimal Price { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<PurchaseHistory> PurchaseHistories { get; set; }
    }
}
