//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerce.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        public User()
        {
            this.PurchaseHistories = new HashSet<PurchaseHistory>();
        }
    
        public int Id { get; set; }
        [Required,MinLength(4,ErrorMessage="Username is too short")]
        public string Username { get; set; }
        [Required,MinLength(4,ErrorMessage="Weak Password")]
        public string Password { get; set; }
        [Required]
        public string Name { get; set; }
        [Required,EmailAddress]
        public string Email { get; set; }
        [Required,Range(1300000000,1999999999,ErrorMessage="Invalid Number")]
        public int Mobile { get; set; }
        [Required]
        public string Address { get; set; }
        public bool IsAdmin { get; set; }
    
        public virtual ICollection<PurchaseHistory> PurchaseHistories { get; set; }
    }
}
